### ISSUE TITLE
Automatically pull and load cogs.

### ISSUE THREAD

**Issue by Fletch617** [Uncle-Sagbag/Kakapo#14]
The bot should constantly be checking the official Github Page and notice an update.
Once an update is noticed, the bot should be able to download the update and load it.

**Comment by Fletch617** [comment]
Sag do you wanna do this since you have the knowledge of SHH and all that shit?

**Comment by Uncle-Sagbag** [comment]
Sure, I'll take over.

**Comment by Uncle-Sagbag** [comment]
I've looked into this but did not get far. There is no reliable way to automatically git pull, it has to be done manually.

On the bright side, now that we separated dev and master, commits would be merged and pulled on the same day.

We can look back to this issue if we find something better. For now, we will close this to get closer to 1.0.0.
