### ISSUE TITLE
Operation Scheduler

### ISSUE THREAD

**Issue by Fletch617** [Uncle-Sagbag/Kakapo#18]
A command to schedule ops in the #scheduling chat. This should take the place people asking if a day is open.

There should be two commands:

!schedule iefjeijfeijfiejfeifr

and 

!calendar

Schedule should be the actual creation of the reservation and calendar should give all of the scheduled operations. The bot should be able to auto delete past reservations.

**Comment by Uncle-Sagbag** [comment]
Seems similar to #9 but with a few more features. See if you can combine this with #9.

**Comment by Uncle-Sagbag** [comment]
No longer necessary due to the neat event system on Discord
