### ISSUE TITLE
Randomly Post Image from #screenshots-n-videos

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Uncle-Sagbag/Kakapo#19]
Original message from THE_SPACEMAN#9984:

> @Pickle423 @Uncle-Sagbag  Can we get a command that randomly posts an image from #screenshots-n-videos ?

The alias would be:

!screenshot !sc
Posts a random screenshot from the #screenshots-n-videos channel.

**Comment by Fletch617** [comment]
Wouldnt we have to do this manually? I mean in the fact that we would have to download all the screenshots and upload them to the server? It would just be a hassle to get new ones.

**Comment by Uncle-Sagbag** [comment]
The server can loop through the channel and download every image file to the server itself. It can do this on ready.

**Comment by Pickle423** [comment]
I don't think the server can do this on_ready, it doesn't seem like nextcord is built to allow bots to go and loop through prior messages. We can set up the bot to automatically download new screenshots as they come in, however, the code for this would be really simple.

**Comment by Pickle423** [comment]
Completed, make sure to make a folder names "attachments" in the bot folder, otherwise it will error out on you.

**Comment by Uncle-Sagbag** [comment]
Current iteration posts recent screenshots rather than pick from all screenshots ever. Is that intended?

**Comment by Uncle-Sagbag** [comment]
Archived feature due to rare usage. Will cancel this ticket accordingly.
