### ISSUE TITLE
Change roles in #react-for-roles

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Uncle-Sagbag/Kakapo#2]
The bot should be able to replace YAGPDB.xyz bot's function of a role selection. Users, new or old, should be able to easily change between Combat Service Support and Operative. They would do this by joining a channel called #react-for-roles and reacting on the appropriate emoji to switch roles.

Below is an image of how the current bot works. Try to emulate it as much as possible.
![image](https://user-images.githubusercontent.com/84741883/135865733-1d6b613e-488e-4c95-a96e-d4103f402d7d.png)

**Comment by Fletch617** [comment]
somewhat finished, when the Emojis and the actual message has been created, then we would need to update this to fit the emojis.

**Comment by Uncle-Sagbag** [comment]
I have been QA testing this today. Encountered the following problem:

I ran `!roleReactMessage` in `#react-for-roles`. The embed message was successfully created but the 1️⃣ and 2️⃣ were repeatedly being created and removed under the embed. I did not react on the message. This is likely the bot detecting itself adding reactions to the message and looping `on_raw_reaction_add` and `on_raw_reaction_remove` on itself.

@Fletch617 Please see `on_raw_reaction_add` and `on_raw_reaction_remove` and add conditions to ignore the event if the Kakapo bot added the reaction.
https://github.com/Uncle-Sagbag/Kakapo/blob/9ad618b1aedd942bbf6bfdfdb9e74e2c5fa0e9c7/cogs/roleReactions.py#L36-L69 https://github.com/Uncle-Sagbag/Kakapo/blob/9ad618b1aedd942bbf6bfdfdb9e74e2c5fa0e9c7/cogs/roleReactions.py#L73-L89
