### ISSUE TITLE
More Game Options?

### ISSUE THREAD

**Issue by ptrevor20** [Uncle-Sagbag/Kakapo#22]
All the bot is playing are stupid games like arma 3, left for dead, and that other game. Can we get more variety please?

I recommend Nekopara, huniepop, and METAL GEAR SOLID V: THE PHANTOM PAIN

Thanks,
P. Trevor

**Comment by ojax1121** [comment]
+1
Would recommend promotion from trial moderator to moderator.

**Comment by Uncle-Sagbag** [comment]
No porn games but we can add Metal Gear Solid V.

**Comment by Uncle-Sagbag** [comment]
Added Metal Gear Solid V in 0651be32dbceec36a633c6d5e287889d255cfb87
