### ISSUE TITLE
War Photographer Role and Command

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Uncle-Sagbag/Kakapo#31]
This is an idea to make screenshot uploads easier for Mace and other screenshot uploaders. There are two parts to this:

---
1. **War Photographer Role**

A new role that will be assigned to one or more SESO operatives on Discord. This role has no special functions and is used for condition checking in part 2.

2. **Upload Screenshot Command**

Use Cases
```
<Operative uploads a file>
Operative> !uploadscreenshot
Kakapo> File successfully uploaded!
```
Aliases
```
!uploadscreenshot
!upload
!usc
!u
```

The command will then download the uploaded file, whatever it may be, and saves it to a folder in the project. The name of the folder to contain these files can be called `war_files`.

Before uploading the file, the bot will check for 2 conditions:
* _Does the operative calling the command have the War Photographer role?_ 
Otherwise, ignore command and respond with error "You do not have the required War Photographer role"
* _Is the file at most 5 GB?_ 
Otherwise, ignore command and respond with error "Could not upload file, exceeded 5 GB file size limit"

If both conditions are true, file will be uploaded to the project's `war_files` folder.

P.S. Assign the filepath to the `war_files` folder to a variable. I will be changing the filepath often and this will be easier when the path is assigned to a variable.

**Comment by Pickle423** [comment]
We don't need to check the file size, as the discord cap is 8mbs
