### ISSUE TITLE
LOA / No Role Functionality for AWOL members 

### ISSUE THREAD

**Issue by Rydero** [Uncle-Sagbag/Kakapo#36]
Currently, I noticed the AWOL function for the bot marks Operatives with the role of LOA, which can be problematic. If possible any Operative with the LOA role should be excluded from being marked for obvious reasons.

 In addition, members of the discord without a role do not seem to be given a role either. Members without any roles  _should_ be marked or straight up removed after an extended period without sending messages or picking roles.

**Comment by Pickle423** [comment]
This is also implemented/fixed in the latest pull request.
