### ISSUE TITLE
Notification for AWOL members

### ISSUE THREAD

**Issue by Rydero** [Uncle-Sagbag/Kakapo#37]
Upon giving any members of S.E.S.O. the AWOL role Kakapo should also notify the person via a DM. Thereby giving the recipient some way of being notified that they have been given the role within the discord. 

This notification should include an explanation of the role of AWOL, a redirect to the #unit-rules where it is explained/paraphrasing of the rules, and how to remove it. (Talking to Command Consultant/Operations Command.)

**Comment by Pickle423** [comment]
This has been added in the upcoming pull request, thanks for the suggestion.
