### ISSUE TITLE
Post engagement reminders

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Uncle-Sagbag/Kakapo#6]
The most complex feature of the Kakapo bot should be the ability to post engagement reminders. This would substitute the announcements people manually post in #engagement-announcements. It also keeps a consistent uniform and prevents unnecessary conversations and spam. 

Only engagement hosts and operations hosts should be able to use this command. It can only be used in #bot-commands, #scheduling, and #host-general.

It should look like the following:

```
!postop
!op
!operation
!engage
!en
!engagement
!posten
!postengagement

1. Kakapo > Are you creating a new operation?
Yes > 2
No > 3

2. Kakapo > What is the name of your operation? Please make sure to start with the word "Operation"
User enters operation name > 3

3. Kakapo > What day is your engagement? Please type it in DD/MM/YYYY
User enters a day, format should be DD/MM/YYYY. Check if it is valid before moving on

4. Kakapo > What time is your engagement? Please type in "military" time or "European format" time ##:##
User enters a time, format should be ##:##, without any PMs or AMs. Check if it is valid before moving on

5. Kakapo > How often do you want to remind operators of this engagement?
> A. Three days before the engagement and including on the day of the engagement
> B. Every week including on the day of the engagement
> C. Every fortnight including on the day of the engagement
> D. Only on the day of the engagement
> E. Do not remind operators
User inputs a letter to select their choice

6. Kakapo > Any extra notes you want to add after the reminder? I.E. which mod preset should they use, where their briefing is, etc.
User inputs their notes. These notes will appear at the end of every reminder.

7. Kakapo > <operation_name> is posted in #engagement-announcements
```

After this exchange, the Kakapo bot will post the reminders according to Question 5. It will repeat the same question and focus on the date & time of the engagement.

After every reminder, send the same message to the caller's DMs. This is to ensure the caller is reminded as well.

**Comment by Pickle423** [comment]
This will be absolutely hellish to make, what have we done to deserve this unjust hell.

**Comment by Uncle-Sagbag** [comment]
Let's keep this issue on hold until we have many engagement hosts again. There is a total of 3 people making engagements anymore, making this feature overkill.

**Comment by Uncle-Sagbag** [comment]
Outdated ticket, using Discord's events and unix timestamps is more than enough for us
