### ISSUE TITLE
Make my own katalam

### ISSUE THREAD

**Issue by Fletch617** [Uncle-Sagbag/Kakapo#8]
I think I could make a system that would serve as a shitty replacement for katalam. This would work with text documents and a loop that would constantly check when new players would be added and so on. It would also post the player list in host channel before the op.

(This would also include working on operation reminders.)

**Comment by Uncle-Sagbag** [comment]
Do you want to leave that for version 2? I'd rather we finish up our existing issues to get version 1 / project 1 done.

**Comment by Fletch617** [comment]
It doesn't really matter when we work on issues and when we implement them in my opinion.

**Comment by Uncle-Sagbag** [comment]
That's true, the order that one could do these issues is arbitrary. But I'd like to be able to use the features in version 1 earlier than the features in version 2. That's why I'd like to prioritize the simpler commands in version 1 then work on more complex features in version 2.

**Comment by Uncle-Sagbag** [comment]
It has been made, check PR https://github.com/Uncle-Sagbag/Kakapo/pull/42
